import React from "react";
import { db } from "./firebase";
import {
  collection,
  writeBatch,
  doc,
  serverTimestamp,
} from "firebase/firestore";

const exercisesData = {
  Exercises: {
    Push: [
      {
        id: 1,
        name: "Barbell Bench Press",
        category: "Push",
        difficulty: "Intermediate",
        sets: 4,
        reps: "8-12",
        restTime: "60-90s",
        musclesTargeted: ["Chest", "Triceps", "Front Delts"],
        equipment: ["Barbell", "Bench"],
        instructions: [
          "Lie flat on bench with feet firmly on floor",
          "Grip barbell slightly wider than shoulder-width",
          "Lower bar to mid-chest with control",
          "Press bar explosively back to starting position",
        ],
        benefits: "Builds overall pushing strength and chest mass",
        image:
          "https://i.postimg.cc/Y05MvGW3/Bench-Press-Warm-Up-Cardio-Stretches-Sets-More.jpg",
        videoLink: "https://i.postimg.cc/zD6JtMcq/download-3.gif",
      },
      {
        id: 2,
        name: "Overhead Press",
        category: "Push",
        difficulty: "Intermediate",
        sets: 4,
        reps: "8-12",
        restTime: "60s",
        musclesTargeted: ["Shoulders", "Triceps", "Upper Chest"],
        equipment: ["Barbell"],
        instructions: [
          "Stand with feet shoulder-width apart",
          "Grip barbell at shoulder level",
          "Press barbell overhead until arms are fully extended",
          "Lower with control to starting position",
        ],
        benefits: "Develops shoulder strength and size",
        image:
          "https://i.postimg.cc/nrbnz97k/Squat-To-Overhead-Press-Video-Guide-Tips-2025.jpg",
        videoLink: "https://i.postimg.cc/KcBZWQhh/download-4.gif",
      },
      {
        id: 3,
        name: "Incline Dumbbell Press",
        category: "Push",
        difficulty: "Intermediate",
        sets: 3,
        reps: "10-12",
        restTime: "60s",
        musclesTargeted: ["Upper Chest", "Front Delts"],
        equipment: ["Dumbbells", "Incline Bench"],
        instructions: [
          "Set bench to 30-45 degree incline",
          "Hold dumbbells at chest level with palms forward",
          "Press dumbbells upward until arms are extended",
          "Lower with control back to start",
        ],
        benefits: "Targets upper chest development",
        image:
          "https://i.postimg.cc/mrHqrXSV/Incline-Bench-Press-Video-Guide-Lyfta.jpg",
        videoLink:
          "https://i.postimg.cc/hGdwGy0w/Incline-Dumbbell-Bench-Press.gif",
      },
      {
        id: 4,
        name: "Dips",
        category: "Push",
        difficulty: "Intermediate",
        sets: 3,
        reps: "8-12",
        restTime: "60s",
        musclesTargeted: ["Chest", "Triceps", "Shoulders"],
        equipment: ["Parallel Bars"],
        instructions: [
          "Grip parallel bars and lift yourself up",
          "Lean forward slightly to emphasize chest",
          "Lower body until shoulders are below elbows",
          "Push back up to starting position",
        ],
        benefits: "Bodyweight exercise for chest and triceps",
        image: "https://i.postimg.cc/y8YShxpr/download-6.jpg",
        videoLink:
          "https://i.postimg.cc/g2SLgp15/Machine-assisted-triceps-dip-New-Life-Health-Center.gif",
      },
      {
        id: 5,
        name: "Tricep Pushdowns",
        category: "Push",
        difficulty: "Beginner",
        sets: 3,
        reps: "12-15",
        restTime: "45s",
        musclesTargeted: ["Triceps"],
        equipment: ["Cable Machine"],
        instructions: [
          "Stand facing cable machine with rope attachment",
          "Grip rope with palms facing each other",
          "Push rope down until arms are fully extended",
          "Return with control to starting position",
        ],
        benefits: "Isolates and develops triceps",
        image: "https://i.postimg.cc/2SCrVX8L/download-7.jpg",
        videoLink:
          "https://i.postimg.cc/6pzwRLy0/Trizeps-Ubungen-im-Uberblick-so-bekommst-Du-grosse-Oberarme.gif",
      },
      {
        id: 6,
        name: "Lateral Raises",
        category: "Push",
        difficulty: "Beginner",
        sets: 3,
        reps: "12-15",
        restTime: "45s",
        musclesTargeted: ["Side Delts"],
        equipment: ["Dumbbells"],
        instructions: [
          "Stand holding dumbbells at sides",
          "Raise arms out to sides until parallel to floor",
          "Keep slight bend in elbows",
          "Lower with control to starting position",
        ],
        benefits: "Develops shoulder width and definition",
        image:
          "https://i.postimg.cc/5ykL6F8V/How-To-Do-Dumbbell-Lateral-Raise-The-Right-Way-2025.jpg",
        videoLink:
          "https://i.postimg.cc/CMvjv9Xt/Seitheben-mit-Kurzhanteln-so-funktioniert-diese-Ubung-richtig.gif",
      },
      {
        id: 7,
        name: "Close Grip Bench Press",
        category: "Push",
        difficulty: "Intermediate",
        sets: 3,
        reps: "8-12",
        restTime: "60s",
        musclesTargeted: ["Triceps", "Chest"],
        equipment: ["Barbell", "Bench"],
        instructions: [
          "Lie on bench with hands close together on barbell",
          "Lower bar to lower chest",
          "Press bar up while keeping elbows close to body",
          "Focus on triceps engagement",
        ],
        benefits: "Targets triceps while involving chest",
        image:
          "https://i.postimg.cc/zXF3thyk/Stockvideoportfolio-van-Makatserchyk-Shutterstock-bijdrager.jpg",
        videoLink:
          "https://i.postimg.cc/mgZk0r9q/Bankdrucken-Langhantel-Top-4-Ausfuhrungen-inkl-Bilder-Videos.gif",
      },
      {
        id: 8,
        name: "Push-Ups",
        category: "Push",
        difficulty: "Beginner",
        sets: 3,
        reps: "15-20",
        restTime: "45s",
        musclesTargeted: ["Chest", "Triceps", "Shoulders"],
        equipment: ["Mat"],
        instructions: [
          "Start in plank position with hands shoulder-width apart",
          "Lower body until chest nearly touches floor",
          "Keep elbows close to body",
          "Push back to starting position",
        ],
        benefits: "Fundamental pushing movement, no equipment needed",
        image: "https://i.postimg.cc/NfsQ0z0g/download-8.jpg",
        videoLink: "https://i.postimg.cc/15vsVrgb/download-5.gif",
      },
      {
        id: 9,
        name: "Arnold Press",
        category: "Push",
        difficulty: "Intermediate",
        sets: 3,
        reps: "10-12",
        restTime: "60s",
        musclesTargeted: ["All Deltoid Heads"],
        equipment: ["Dumbbells"],
        instructions: [
          "Sit on bench with back support",
          "Start with dumbbells at shoulder height, palms facing you",
          "Press upward while rotating palms to face forward",
          "Reverse motion on the way down",
        ],
        benefits: "Comprehensive shoulder development",
        image:
          "https://i.postimg.cc/NfSCnKZh/How-To-Do-An-Arnold-Dumbbell-Press-For-Schwarzenegger-Shoulders.jpg",
        videoLink: "https://i.postimg.cc/4Nq20YjG/download-6.gif",
      },
      {
        id: 10,
        name: "Cable Crossovers",
        category: "Push",
        difficulty: "Intermediate",
        sets: 3,
        reps: "12-15",
        restTime: "45s",
        musclesTargeted: ["Inner Chest", "Pectorals"],
        equipment: ["Cable Machine"],
        instructions: [
          "Set cables to high position",
          "Stand in middle with one handle in each hand",
          "Bring hands together in front of chest",
          "Return with control to starting position",
        ],
        benefits: "Isolates chest and creates definition",
        image: "https://i.postimg.cc/SQwtTXBy/High-Cable-Crossover.jpg",
        videoLink:
          "https://i.postimg.cc/t4bvbKRw/Brust-Ubungen-im-Uberblick-so-bekommst-Du-eine-breite-Brust.gif",
      },
    ],

    Pull: [
      {
        id: 1,
        name: "Pull-Ups",
        category: "Pull",
        difficulty: "Intermediate",
        sets: 3,
        reps: "6-10",
        restTime: "60s",
        musclesTargeted: ["Lats", "Biceps", "Rhomboids"],
        equipment: ["Pull-up Bar"],
        instructions: [
          "Grip bar slightly wider than shoulder-width",
          "Hang with arms fully extended",
          "Pull body up until chin clears bar",
          "Lower with control to starting position",
        ],
        benefits: "Builds back width and upper body strength",
        image:
          "https://i.postimg.cc/SQC72GVS/19_Best_Back_Exercises_for_Getting_a_Coveted_V_Shaped_Torso_Building_Strength_and_Preventing_Injur.jpg",
        videoLink: "https://i.postimg.cc/gjWhqf4P/download_(7).gif",
      },
      {
        id: 2,
        name: "Bent-Over Rows",
        category: "Pull",
        difficulty: "Intermediate",
        sets: 4,
        reps: "8-12",
        restTime: "60s",
        musclesTargeted: ["Lats", "Rhomboids", "Rear Delts"],
        equipment: ["Barbell"],
        instructions: [
          "Stand with feet shoulder-width apart",
          "Bend knees slightly and hinge at hips",
          "Grip barbell with overhand grip",
          "Pull bar to lower chest, squeeze back muscles",
        ],
        benefits: "Develops back thickness and posture",
        image: "https://i.postimg.cc/wThyBFXt/download_(13).jpg",
        videoLink: "https://i.postimg.cc/L8xsqWnY/download_(13).gif",
      },
      {
        id: 3,
        name: "Deadlifts",
        category: "Pull",
        difficulty: "Advanced",
        sets: 3,
        reps: "5-8",
        restTime: "90-120s",
        musclesTargeted: ["Lower Back", "Glutes", "Hamstrings", "Full Back"],
        equipment: ["Barbell"],
        instructions: [
          "Stand with feet hip-width apart, barbell over mid-foot",
          "Bend at hips and knees to grip bar",
          "Keep back straight and lift bar by extending hips",
          "Stand tall, then lower bar with control",
        ],
        benefits: "Full body compound movement, builds overall strength",
        image:
          "https://i.postimg.cc/hj6BkBNR/Block-Pull-Deadlift-Benefits-Muscles-Used-and-More.jpg",
        videoLink: "https://i.postimg.cc/NFd1sd7w/download-(9).gif",
      },
      {
        id: 4,
        name: "Lat Pulldowns",
        category: "Pull",
        difficulty: "Beginner",
        sets: 3,
        reps: "10-12",
        restTime: "45s",
        musclesTargeted: ["Lats", "Biceps", "Upper Back"],
        equipment: ["Cable Machine"],
        instructions: [
          "Sit at lat pulldown machine",
          "Grip bar wider than shoulder-width",
          "Pull bar down to upper chest",
          "Return with control to starting position",
        ],
        benefits: "Excellent for building back width",
        image: "https://i.postimg.cc/FKXGnnTM/download-(10).jpg",
        videoLink: "https://i.postimg.cc/mgz6n9BC/download_(10).gif",
      },
      {
        id: 5,
        name: "Seated Cable Rows",
        category: "Pull",
        difficulty: "Intermediate",
        sets: 3,
        reps: "10-12",
        restTime: "45s",
        musclesTargeted: ["Middle Back", "Rhomboids", "Lats"],
        equipment: ["Cable Machine"],
        instructions: [
          "Sit at cable row machine with feet braced",
          "Grip handle with neutral grip",
          "Pull handle to abdomen, squeeze shoulder blades",
          "Return with control to starting position",
        ],
        benefits: "Targets middle back for thickness",
        image: "https://i.postimg.cc/Njq1g2Rg/download_(11).jpg",
        videoLink: "https://i.postimg.cc/0N9DSgtX/download_(11).gif",
      },
      {
        id: 6,
        name: "Face Pulls",
        category: "Pull",
        difficulty: "Intermediate",
        sets: 3,
        reps: "15-20",
        restTime: "45s",
        musclesTargeted: ["Rear Delts", "Upper Back"],
        equipment: ["Cable Machine"],
        instructions: [
          "Set cable at upper chest height",
          "Grip rope attachment with both hands",
          "Pull rope towards face, separating hands at end",
          "Squeeze rear delts and upper back",
        ],
        benefits: "Improves posture and rear delt development",
        image: "https://i.postimg.cc/BZFTRC1r/Face_pull.jpg",
        videoLink:
          "https://i.postimg.cc/3JHXhDXQ/20_Best_Cable_Machine_Exercises_(With_Workout_Routines).gif",
      },
      {
        id: 7,
        name: "Bicep Curls",
        category: "Pull",
        difficulty: "Beginner",
        sets: 3,
        reps: "12-15",
        restTime: "45s",
        musclesTargeted: ["Biceps"],
        equipment: ["Dumbbells"],
        instructions: [
          "Stand holding dumbbells at sides with palms forward",
          "Curl one arm up towards shoulder",
          "Squeeze bicep at top of movement",
          "Lower with control and alternate arms",
        ],
        benefits: "Builds bicep size and strength",
        image: "https://i.postimg.cc/bY0GQVnn/download_(12).jpg",
        videoLink: "https://i.postimg.cc/441dK7CZ/download_(12).gif",
      },
      {
        id: 8,
        name: "Hammer Curls",
        category: "Pull",
        difficulty: "Beginner",
        sets: 3,
        reps: "12-15",
        restTime: "45s",
        musclesTargeted: ["Brachialis", "Forearms"],
        equipment: ["Dumbbells"],
        instructions: [
          "Stand holding dumbbells with palms facing each other",
          "Curl both arms up simultaneously",
          "Keep palms facing each other throughout movement",
          "Lower with control to starting position",
        ],
        benefits: "Builds arm thickness and forearm strength",
        image: "https://i.postimg.cc/kG6z7BLB/Hammer_Curls.jpg",
        videoLink:
          "https://i.postimg.cc/sfMgMKRk/Bizeps_Training_die_8_besten_Bizeps_Übungen_fürs_Gym.gif",
      },
      {
        id: 9,
        name: "T-Bar Rows",
        category: "Pull",
        difficulty: "Intermediate",
        sets: 3,
        reps: "8-12",
        restTime: "60s",
        musclesTargeted: ["Middle Back", "Lats", "Rhomboids"],
        equipment: ["T-Bar Machine", "Barbell"],
        instructions: [
          "Stand over T-bar or loaded barbell",
          "Bend at hips with back straight",
          "Pull weight towards chest",
          "Squeeze back muscles at top",
        ],
        benefits: "Great for back thickness and strength",
        image: "https://i.postimg.cc/Bbz0GGyq/download_(9).jpg",
        videoLink: "https://i.postimg.cc/CKS9X11G/download_(8).gif",
      },
    ],

    Abs: [
      {
        id: 1,
        name: "Crunches",
        category: "Abs",
        difficulty: "Beginner",
        sets: 3,
        reps: "15-20",
        restTime: "30s",
        musclesTargeted: ["Upper Abs", "Core"],
        equipment: ["Mat"],
        instructions: [
          "Lie on your back with knees bent and feet flat on the floor",
          "Place hands behind your head or cross them on your chest",
          "Lift your upper body towards your knees",
          "Slowly lower back down",
        ],
        benefits: "Strengthens upper abdominal muscles",
        image:
          "https://i.postimg.cc/tR8vbRk3/The_Workout_That_Demolishes_Body_Fat.jpg",
        videoLink:
          "https://i.postimg.cc/50Y5KvZF/Crunch_uitvoering_en_uitleg_Men_s_Power.gif",
      },
      {
        id: 2,
        name: "Leg Raises",
        category: "Abs",
        difficulty: "Intermediate",
        sets: 3,
        reps: "12-15",
        restTime: "45s",
        musclesTargeted: ["Lower Abs", "Core"],
        equipment: ["Mat"],
        instructions: [
          "Lie flat on your back with legs straight",
          "Place hands under your glutes for support",
          "Lift legs straight up until perpendicular to floor",
          "Slowly lower legs back down without touching floor",
        ],
        benefits: "Targets lower abdominal muscles effectively",
        image:
          "https://i.postimg.cc/vBKybR24/Leg_Raises_Variaties_voor_Beginners_en_Gevorderden_Info_Fitness.jpg",
        videoLink:
          "https://i.postimg.cc/NFrc0NZf/Chest_Abs_Workout_Routine_Created_By_Kuzey.gif",
      },
      {
        id: 3,
        name: "Plank",
        category: "Abs",
        difficulty: "Beginner",
        sets: 3,
        reps: "30-60 seconds",
        restTime: "30s",
        musclesTargeted: ["Core", "Full Abs", "Shoulders"],
        equipment: ["Mat"],
        instructions: [
          "Start in push-up position with elbows under shoulders",
          "Keep body in straight line from head to heels",
          "Engage core and hold position",
          "Don't let hips sag or rise",
        ],
        benefits: "Builds core strength and stability",
        image:
          "https://i.postimg.cc/VN6L8Fs4/10_Best_Core_Exercises_for_Beginners_(With_Home_Workout_Plan).jpg",
        videoLink: "https://i.postimg.cc/FKRs4xFW/download_(14).gif",
      },
      {
        id: 4,
        name: "Russian Twists",
        category: "Abs",
        difficulty: "Intermediate",
        sets: 3,
        reps: "15-20 each side",
        restTime: "45s",
        musclesTargeted: ["Obliques", "Core"],
        equipment: ["Mat", "Weight (optional)"],
        instructions: [
          "Sit on floor with knees bent and feet elevated",
          "Lean back slightly keeping back straight",
          "Twist torso from side to side",
          "Keep core engaged throughout movement",
        ],
        benefits: "Develops oblique muscles and rotational strength",
        image:
          "https://i.postimg.cc/rm4TVnBd/6_Best_Russian_Twist_Alternatives_with_Pictures.jpg",
        videoLink: "https://i.postimg.cc/G2DRL7WD/Russian_Twist.gif",
      },
      {
        id: 5,
        name: "Mountain Climbers",
        category: "Abs",
        difficulty: "Intermediate",
        sets: 3,
        reps: "20-30 each leg",
        restTime: "45s",
        musclesTargeted: ["Core", "Full Abs", "Cardio"],
        equipment: ["Mat"],
        instructions: [
          "Start in plank position",
          "Bring one knee towards chest",
          "Quickly switch legs in running motion",
          "Maintain steady pace and tight core",
        ],
        benefits: "Combines core strength with cardio",
        image:
          "https://i.postimg.cc/qqG9q9jB/The_Complete_Guide_to_Ab_Workout_at_Home.jpg",
        videoLink:
          "https://i.postimg.cc/Y2fcdWMB/Treino_para_Perder_Barriga_Guia_Completo_para_um_Abdômen_Definido_em_2025.gif",
      },
      {
        id: 6,
        name: "Bicycle Crunches",
        category: "Abs",
        difficulty: "Intermediate",
        sets: 3,
        reps: "20-30 each side",
        restTime: "45s",
        musclesTargeted: ["Obliques", "Upper Abs", "Lower Abs"],
        equipment: ["Mat"],
        instructions: [
          "Lie on back with hands behind head",
          "Bring right elbow to left knee while extending right leg",
          "Alternate sides in pedaling motion",
          "Keep core engaged throughout",
        ],
        benefits: "Targets entire abdominal wall and obliques",
        image: "https://i.postimg.cc/bvbVd7vz/Bicycle_Crunch.jpg",
        videoLink: "https://i.postimg.cc/wMW0SHwj/download_(15).gif",
      },
      {
        id: 7,
        name: "Hanging Leg Raises",
        category: "Abs",
        difficulty: "Advanced",
        sets: 3,
        reps: "10-15",
        restTime: "60s",
        musclesTargeted: ["Lower Abs", "Hip Flexors", "Core"],
        equipment: ["Pull-up Bar"],
        instructions: [
          "Hang from pull-up bar with arms extended",
          "Raise legs straight up until parallel to floor",
          "Lower legs with control",
          "Avoid swinging body",
        ],
        benefits: "Advanced lower ab development",
        image:
          "https://i.postimg.cc/GtNvFp7n/Hanging_Leg_Raises_for_strong_a_Abdomen_and_Hip_Flexors.jpg",
        videoLink:
          "https://i.postimg.cc/T2HjMkRr/https_fitnessprogramer_com_wp_content_uploads_2021_02_Hanging_Knee_Raises.gif",
      },
      {
        id: 8,
        name: "Ab Rollout",
        category: "Abs",
        difficulty: "Advanced",
        sets: 3,
        reps: "8-12",
        restTime: "60s",
        musclesTargeted: ["Full Abs", "Core Stability"],
        equipment: ["Ab Wheel"],
        instructions: [
          "Kneel on floor holding ab wheel",
          "Roll forward until body is extended",
          "Keep core tight and back straight",
          "Roll back to starting position",
        ],
        benefits: "Builds exceptional core strength",
        image: "https://i.postimg.cc/rs6rsHzg/download_(14).jpg",
        videoLink: "https://i.postimg.cc/Vk70nvdV/download_(16).gif",
      },
      {
        id: 9,
        name: "Flutter Kicks",
        category: "Abs",
        difficulty: "Beginner",
        sets: 3,
        reps: "30-45 seconds",
        restTime: "30s",
        musclesTargeted: ["Lower Abs", "Hip Flexors"],
        equipment: ["Mat"],
        instructions: [
          "Lie on back with legs extended",
          "Lift legs slightly off floor",
          "Alternate kicking legs up and down",
          "Keep lower back pressed to floor",
        ],
        benefits: "Targets lower abs and improves endurance",
        image:
          "https://i.postimg.cc/HW2YVKJV/18_Lower_Ab_Exercises_That_Actually_Work.jpg",
        videoLink:
          "https://i.postimg.cc/QNb8HPBc/Flutter_Kicks_für_Bauch_oder_Po_modus_X.gif",
      },
      {
        id: 10,
        name: "Side Plank",
        category: "Abs",
        difficulty: "Intermediate",
        sets: 3,
        reps: "30-45 seconds each side",
        restTime: "30s",
        musclesTargeted: ["Obliques", "Side Core"],
        equipment: ["Mat"],
        instructions: [
          "Lie on side with legs straight",
          "Prop up on elbow with forearm perpendicular to body",
          "Lift hips to form straight line from head to feet",
          "Hold position engaging obliques",
        ],
        benefits: "Develops oblique strength and stability",
        image: "https://i.postimg.cc/TPMMkqyB/Side-Plank.jpg",
        videoLink: "https://i.postimg.cc/TPMMkqyB/Side-Plank.jpg",
      },
      {
        id: 11,
        name: "Reverse Crunches",
        category: "Abs",
        difficulty: "Intermediate",
        sets: 3,
        reps: "15-20",
        restTime: "45s",
        musclesTargeted: ["Lower Abs"],
        equipment: ["Mat"],
        instructions: [
          "Lie on back with knees bent at 90 degrees",
          "Place hands at sides or under glutes",
          "Lift hips off floor towards chest",
          "Lower with control back to start",
        ],
        benefits: "Isolates lower abdominal muscles",
        image:
          "https://i.postimg.cc/HsqhHWpK/18_Lower_Ab_Exercises_That_Actually_Work_(1).jpg",
        videoLink:
          "https://i.postimg.cc/jSykjV59/Reverse_Crunches_Varianten_mit_und_ohne_Bank_modus_X.gif",
      },
    ],

    Chest: [
      {
        id: 1,
        name: "Bench Press",
        category: "Chest",
        difficulty: "Intermediate",
        sets: 4,
        reps: "8-12",
        restTime: "60-90s",
        musclesTargeted: ["Pectoralis Major", "Triceps", "Front Delts"],
        equipment: ["Barbell", "Bench"],
        instructions: [
          "Lie flat on bench with feet on floor",
          "Grip barbell slightly wider than shoulder-width",
          "Lower bar to mid-chest with control",
          "Press bar back to starting position",
        ],
        benefits: "Builds overall chest mass and strength",
        image:
          "https://i.postimg.cc/Y05MvGW3/Bench-Press-Warm-Up-Cardio-Stretches-Sets-More.jpg",
        videoLink: "https://i.postimg.cc/zD6JtMcq/download-3.gif",
      },
      {
        id: 2,
        name: "Incline Dumbbell Press",
        category: "Chest",
        difficulty: "Intermediate",
        sets: 3,
        reps: "10-12",
        restTime: "60s",
        musclesTargeted: ["Upper Chest", "Front Delts"],
        equipment: ["Dumbbells", "Incline Bench"],
        instructions: [
          "Set bench to 30-45 degree incline",
          "Hold dumbbells at chest level with palms forward",
          "Press dumbbells upward until arms are extended",
          "Lower with control back to start",
        ],
        benefits: "Targets upper chest development",
        image:
          "https://i.postimg.cc/mrHqrXSV/Incline-Bench-Press-Video-Guide-Lyfta.jpg",
        videoLink:
          "https://i.postimg.cc/hGdwGy0w/Incline-Dumbbell-Bench-Press.gif",
      },
      {
        id: 3,
        name: "Push-Ups",
        category: "Chest",
        difficulty: "Beginner",
        sets: 3,
        reps: "15-20",
        restTime: "45s",
        musclesTargeted: ["Chest", "Triceps", "Shoulders"],
        equipment: ["Mat"],
        instructions: [
          "Start in plank position with hands shoulder-width apart",
          "Lower body until chest nearly touches floor",
          "Keep elbows close to body",
          "Push back to starting position",
        ],
        benefits: "Bodyweight chest builder, no equipment needed",
        image: "https://i.postimg.cc/NfsQ0z0g/download-8.jpg",
        videoLink: "https://i.postimg.cc/15vsVrgb/download-5.gif",
      },
      {
        id: 4,
        name: "Cable Crossovers",
        category: "Chest",
        difficulty: "Intermediate",
        sets: 3,
        reps: "12-15",
        restTime: "45s",
        musclesTargeted: ["Inner Chest", "Pectorals"],
        equipment: ["Cable Machine"],
        instructions: [
          "Set cables to high position",
          "Stand in middle with one handle in each hand",
          "Bring hands together in front of chest",
          "Return with control to starting position",
        ],
        benefits: "Isolates chest and creates chest definition",
        image: "https://i.postimg.cc/SQwtTXBy/High-Cable-Crossover.jpg",
        videoLink:
          "https://i.postimg.cc/t4bvbKRw/Brust-Ubungen-im-Uberblick-so-bekommst-Du-eine-breite-Brust.gif",
      },
      {
        id: 5,
        name: "Dips",
        category: "Chest",
        difficulty: "Advanced",
        sets: 3,
        reps: "8-12",
        restTime: "60s",
        musclesTargeted: ["Lower Chest", "Triceps", "Shoulders"],
        equipment: ["Parallel Bars"],
        instructions: [
          "Grip parallel bars and lift yourself up",
          "Lean forward slightly to emphasize chest",
          "Lower body until shoulders are below elbows",
          "Push back up to starting position",
        ],
        benefits: "Builds lower chest and triceps strength",
        image: "https://i.postimg.cc/y8YShxpr/download-6.jpg",
        videoLink:
          "https://i.postimg.cc/g2SLgp15/Machine-assisted-triceps-dip-New-Life-Health-Center.gif",
      },
      {
        id: 6,
        name: "Decline Bench Press",
        category: "Chest",
        difficulty: "Intermediate",
        sets: 3,
        reps: "8-12",
        restTime: "60s",
        musclesTargeted: ["Lower Chest", "Triceps"],
        equipment: ["Barbell", "Decline Bench"],
        instructions: [
          "Secure yourself on decline bench",
          "Grip barbell slightly wider than shoulders",
          "Lower bar to lower chest area",
          "Press back to starting position",
        ],
        benefits: "Targets lower pectoral development",
        image:
          "https://i.postimg.cc/Y05MvGW3/Bench_Press_Warm_Up_Cardio_Stretches_Sets_More.jpg",
        videoLink: "https://i.postimg.cc/zD6JtMcq/download_3.gif",
      },
      {
        id: 7,
        name: "Pec Deck Machine",
        category: "Chest",
        difficulty: "Beginner",
        sets: 3,
        reps: "12-15",
        restTime: "45s",
        musclesTargeted: ["Inner Chest", "Pectorals"],
        equipment: ["Pec Deck Machine"],
        instructions: [
          "Sit in machine with back against pad",
          "Grip handles with elbows bent",
          "Bring handles together in front of chest",
          "Return with control to starting position",
        ],
        benefits: "Isolates chest muscles effectively",
        image: "https://i.postimg.cc/vmFTWnG3/download_(15).jpg",
        videoLink: "https://i.postimg.cc/25Q6T55F/download_(17).gif",
      },
      {
        id: 8,
        name: "Dumbbell Flyes",
        category: "Chest",
        difficulty: "Intermediate",
        sets: 3,
        reps: "12-15",
        restTime: "45s",
        musclesTargeted: ["Chest Stretch", "Pectorals"],
        equipment: ["Dumbbells", "Bench"],
        instructions: [
          "Lie on bench with dumbbells above chest",
          "Lower dumbbells out to sides in arc motion",
          "Keep slight bend in elbows",
          "Bring dumbbells back together above chest",
        ],
        benefits: "Excellent for chest stretch and definition",
        image: "https://i.postimg.cc/vHxG3mqS/Dumbbell_Decline_Fly.jpg",
        videoLink: "https://i.postimg.cc/QNw3938F/download_(18).gif",
      },
      {
        id: 9,
        name: "Incline Cable Flyes",
        category: "Chest",
        difficulty: "Intermediate",
        sets: 3,
        reps: "12-15",
        restTime: "45s",
        musclesTargeted: ["Upper Chest", "Pectorals"],
        equipment: ["Cable Machine", "Incline Bench"],
        instructions: [
          "Set bench to incline between cables",
          "Grip handles with palms facing forward",
          "Bring handles together above chest",
          "Return with control to starting position",
        ],
        benefits: "Constant tension on upper chest",
        image: "https://i.postimg.cc/SQwtTXBy/High_Cable_Crossover.jpg",
        videoLink:
          "https://i.postimg.cc/t4bvbKRw/Brust_Ubungen_im_Uberblick_so_bekommst_Du_eine_breite_Brust.gif",
      },
      {
        id: 10,
        name: "Close Grip Bench Press",
        category: "Chest",
        difficulty: "Intermediate",
        sets: 3,
        reps: "8-12",
        restTime: "60s",
        musclesTargeted: ["Triceps", "Inner Chest"],
        equipment: ["Barbell", "Bench"],
        instructions: [
          "Lie on bench with hands close together",
          "Lower bar to lower chest",
          "Press up while keeping elbows close",
          "Focus on triceps and inner chest",
        ],
        benefits: "Emphasizes triceps and inner chest",
        image:
          "https://i.postimg.cc/zXF3thyk/Stockvideoportfolio-van-Makatserchyk-Shutterstock-bijdrager.jpg",
        videoLink:
          "https://i.postimg.cc/mgZk0r9q/Bankdrucken-Langhantel-Top-4-Ausfuhrungen-inkl-Bilder-Videos.gif",
      },
      {
        id: 11,
        name: "Push-Up Variations",
        category: "Chest",
        difficulty: "Intermediate",
        sets: 3,
        reps: "10-15",
        restTime: "45s",
        musclesTargeted: ["Chest", "Triceps", "Core"],
        equipment: ["Mat"],
        instructions: [
          "Perform decline push-ups with feet elevated",
          "Try diamond push-ups for triceps emphasis",
          "Wide grip push-ups for chest stretch",
          "Alternate between variations",
        ],
        benefits: "Versatile chest development with bodyweight",
        image: "https://i.postimg.cc/NfsQ0z0g/download-8.jpg",
        videoLink: "https://i.postimg.cc/15vsVrgb/download-5.gif",
      },
    ],

    Back: [
      {
        id: 1,
        name: "Pull-Ups",
        category: "Back",
        difficulty: "Intermediate",
        sets: 3,
        reps: "6-10",
        restTime: "60s",
        musclesTargeted: ["Lats", "Biceps", "Rhomboids"],
        equipment: ["Pull-up Bar"],
        instructions: [
          "Grip bar slightly wider than shoulder-width",
          "Hang with arms fully extended",
          "Pull body up until chin clears bar",
          "Lower with control to starting position",
        ],
        benefits: "Builds back width and overall upper body strength",
        image:
          "https://i.postimg.cc/SQC72GVS/19_Best_Back_Exercises_for_Getting_a_Coveted_V_Shaped_Torso_Building_Strength_and_Preventing_Injur.jpg",
        videoLink: "https://i.postimg.cc/gjWhqf4P/download_(7).gif",
      },
      {
        id: 2,
        name: "Bent-Over Rows",
        category: "Back",
        difficulty: "Intermediate",
        sets: 4,
        reps: "8-12",
        restTime: "60s",
        musclesTargeted: ["Lats", "Rhomboids", "Rear Delts"],
        equipment: ["Barbell"],
        instructions: [
          "Stand with feet shoulder-width apart",
          "Bend knees slightly and hinge at hips",
          "Grip barbell with overhand grip",
          "Pull bar to lower chest, squeeze back muscles",
        ],
        benefits: "Develops back thickness and posture",
        image: "https://i.postimg.cc/wThyBFXt/download_(13).jpg",
        videoLink: "https://i.postimg.cc/L8xsqWnY/download_(13).gif",
      },
      {
        id: 3,
        name: "Lat Pulldowns",
        category: "Back",
        difficulty: "Beginner",
        sets: 3,
        reps: "10-12",
        restTime: "45s",
        musclesTargeted: ["Lats", "Biceps", "Upper Back"],
        equipment: ["Cable Machine"],
        instructions: [
          "Sit at lat pulldown machine",
          "Grip bar wider than shoulder-width",
          "Pull bar down to upper chest",
          "Return with control to starting position",
        ],
        benefits: "Excellent for building back width",
        image: "https://i.postimg.cc/FKXGnnTM/download-(10).jpg",
        videoLink: "https://i.postimg.cc/mgz6n9BC/download_(10).gif",
      },
      {
        id: 4,
        name: "Deadlifts",
        category: "Back",
        difficulty: "Advanced",
        sets: 3,
        reps: "5-8",
        restTime: "90-120s",
        musclesTargeted: ["Lower Back", "Glutes", "Hamstrings", "Full Back"],
        equipment: ["Barbell"],
        instructions: [
          "Stand with feet hip-width apart, barbell over mid-foot",
          "Bend at hips and knees to grip bar",
          "Keep back straight and lift bar by extending hips",
          "Stand tall, then lower bar with control",
        ],
        benefits: "Full body compound movement, builds overall strength",
        image:
          "https://i.postimg.cc/hj6BkBNR/Block-Pull-Deadlift-Benefits-Muscles-Used-and-More.jpg",
        videoLink: "https://i.postimg.cc/NFd1sd7w/download-(9).gif",
      },
      {
        id: 5,
        name: "Seated Cable Rows",
        category: "Back",
        difficulty: "Intermediate",
        sets: 3,
        reps: "10-12",
        restTime: "45s",
        musclesTargeted: ["Middle Back", "Rhomboids", "Lats"],
        equipment: ["Cable Machine"],
        instructions: [
          "Sit at cable row machine with feet braced",
          "Grip handle with neutral grip",
          "Pull handle to abdomen, squeeze shoulder blades",
          "Return with control to starting position",
        ],
        benefits: "Targets middle back for thickness",
        image: "https://i.postimg.cc/Njq1g2Rg/download_(11).jpg",
        videoLink: "https://i.postimg.cc/0N9DSgtX/download_(11).gif",
      },
      {
        id: 6,
        name: "T-Bar Rows",
        category: "Back",
        difficulty: "Intermediate",
        sets: 3,
        reps: "8-12",
        restTime: "60s",
        musclesTargeted: ["Middle Back", "Lats", "Rhomboids"],
        equipment: ["T-Bar Machine"],
        instructions: [
          "Stand over T-bar machine",
          "Bend at hips with back straight",
          "Pull weight towards chest",
          "Squeeze back muscles at top",
        ],
        benefits: "Great for back thickness and strength",
        image: "https://i.postimg.cc/Bbz0GGyq/download_(9).jpg",
        videoLink: "https://i.postimg.cc/CKS9X11G/download_(8).gif",
      },
      {
        id: 7,
        name: "Single-Arm Dumbbell Rows",
        category: "Back",
        difficulty: "Intermediate",
        sets: 3,
        reps: "10-12 each arm",
        restTime: "45s",
        musclesTargeted: ["Lats", "Rhomboids", "Rear Delts"],
        equipment: ["Dumbbells", "Bench"],
        instructions: [
          "Place one knee and hand on bench",
          "Hold dumbbell in other hand with arm extended",
          "Pull dumbbell to hip, keeping elbow close",
          "Lower with control to starting position",
        ],
        benefits: "Allows for greater range of motion",
        image: "https://i.postimg.cc/7YzfbXkq/Single_arm_dumbbell_row.jpg",
        videoLink: "https://i.postimg.cc/J4XGtKLG/Remo_Unilateral_en_Banco.gif",
      },
      {
        id: 8,
        name: "Face Pulls",
        category: "Back",
        difficulty: "Intermediate",
        sets: 3,
        reps: "15-20",
        restTime: "45s",
        musclesTargeted: ["Rear Delts", "Upper Back"],
        equipment: ["Cable Machine"],
        instructions: [
          "Set cable at upper chest height",
          "Grip rope attachment with both hands",
          "Pull rope towards face, separating hands at end",
          "Squeeze rear delts and upper back",
        ],
        benefits: "Improves posture and rear delt development",
        image: "https://i.postimg.cc/BZFTRC1r/Face_pull.jpg",
        videoLink:
          "https://i.postimg.cc/3JHXhDXQ/20_Best_Cable_Machine_Exercises_(With_Workout_Routines).gif",
      },
    ],

    Shoulders: [
      {
        id: 1,
        name: "Overhead Press",
        category: "Shoulders",
        difficulty: "Intermediate",
        sets: 4,
        reps: "8-12",
        restTime: "60s",
        musclesTargeted: ["Front Delts", "Side Delts", "Triceps"],
        equipment: ["Barbell"],
        instructions: [
          "Stand with feet shoulder-width apart",
          "Grip barbell at shoulder level",
          "Press barbell overhead until arms are fully extended",
          "Lower with control to starting position",
        ],
        benefits: "Builds overall shoulder mass and strength",
        image: "",
        videoLink: "",
      },
      {
        id: 2,
        name: "Lateral Raises",
        category: "Shoulders",
        difficulty: "Beginner",
        sets: 3,
        reps: "12-15",
        restTime: "45s",
        musclesTargeted: ["Side Delts"],
        equipment: ["Dumbbells"],
        instructions: [
          "Stand holding dumbbells at sides",
          "Raise arms out to sides until parallel to floor",
          "Keep slight bend in elbows",
          "Lower with control to starting position",
        ],
        benefits: "Develops shoulder width and definition",
        image: "",
        videoLink: "",
      },
      {
        id: 3,
        name: "Front Raises",
        category: "Shoulders",
        difficulty: "Beginner",
        sets: 3,
        reps: "12-15",
        restTime: "45s",
        musclesTargeted: ["Front Delts"],
        equipment: ["Dumbbells"],
        instructions: [
          "Stand holding dumbbells in front of thighs",
          "Raise one arm forward until parallel to floor",
          "Alternate arms or do both simultaneously",
          "Lower with control to starting position",
        ],
        benefits: "Targets front shoulder development",
        image: "",
        videoLink: "",
      },
      {
        id: 4,
        name: "Face Pulls",
        category: "Shoulders",
        difficulty: "Intermediate",
        sets: 3,
        reps: "15-20",
        restTime: "45s",
        musclesTargeted: ["Rear Delts", "Upper Back"],
        equipment: ["Cable Machine"],
        instructions: [
          "Set cable at upper chest height",
          "Grip rope attachment with both hands",
          "Pull rope towards face, separating hands at end",
          "Squeeze rear delts and upper back",
        ],
        benefits: "Improves posture and rear delt development",
        image: "",
        videoLink: "",
      },
      {
        id: 5,
        name: "Arnold Press",
        category: "Shoulders",
        difficulty: "Intermediate",
        sets: 3,
        reps: "10-12",
        restTime: "60s",
        musclesTargeted: ["All Deltoid Heads"],
        equipment: ["Dumbbells"],
        instructions: [
          "Sit on bench with back support",
          "Start with dumbbells at shoulder height, palms facing you",
          "Press upward while rotating palms to face forward",
          "Reverse motion on the way down",
        ],
        benefits: "Targets all three deltoid heads comprehensively",
        image: "",
        videoLink: "",
      },
      {
        id: 6,
        name: "Upright Rows",
        category: "Shoulders",
        difficulty: "Intermediate",
        sets: 3,
        reps: "10-12",
        restTime: "45s",
        musclesTargeted: ["Side Delts", "Traps"],
        equipment: ["Barbell", "Dumbbells"],
        instructions: [
          "Stand holding barbell or dumbbells with close grip",
          "Pull weight up towards chin",
          "Keep elbows high and wide",
          "Lower with control to starting position",
        ],
        benefits: "Builds side delts and upper traps",
        image: "",
        videoLink: "",
      },
      {
        id: 7,
        name: "Reverse Flyes",
        category: "Shoulders",
        difficulty: "Intermediate",
        sets: 3,
        reps: "12-15",
        restTime: "45s",
        musclesTargeted: ["Rear Delts", "Upper Back"],
        equipment: ["Dumbbells"],
        instructions: [
          "Bend at hips with back straight",
          "Hold dumbbells with palms facing each other",
          "Raise arms out to sides squeezing rear delts",
          "Lower with control to starting position",
        ],
        benefits: "Isolates rear deltoid development",
        image: "",
        videoLink: "",
      },
      {
        id: 8,
        name: "Dumbbell Shoulder Press",
        category: "Shoulders",
        difficulty: "Intermediate",
        sets: 4,
        reps: "8-12",
        restTime: "60s",
        musclesTargeted: ["All Deltoid Heads", "Triceps"],
        equipment: ["Dumbbells"],
        instructions: [
          "Sit on bench with back support",
          "Hold dumbbells at shoulder level",
          "Press dumbbells overhead until arms extended",
          "Lower with control to starting position",
        ],
        benefits: "Allows for natural movement pattern",
        image: "",
        videoLink: "",
      },
      {
        id: 9,
        name: "Cable Lateral Raises",
        category: "Shoulders",
        difficulty: "Intermediate",
        sets: 3,
        reps: "12-15",
        restTime: "45s",
        musclesTargeted: ["Side Delts"],
        equipment: ["Cable Machine"],
        instructions: [
          "Stand next to cable machine with low pulley",
          "Grip handle with opposite hand",
          "Raise arm out to side keeping slight bend",
          "Lower with control to starting position",
        ],
        benefits: "Constant tension on side delts",
        image: "",
        videoLink: "",
      },
      {
        id: 10,
        name: "Shrugs",
        category: "Shoulders",
        difficulty: "Beginner",
        sets: 4,
        reps: "12-15",
        restTime: "45s",
        musclesTargeted: ["Traps", "Upper Back"],
        equipment: ["Barbell", "Dumbbells"],
        instructions: [
          "Stand holding weights at sides",
          "Shrug shoulders up towards ears",
          "Squeeze traps at top position",
          "Lower with control to starting position",
        ],
        benefits: "Builds trapezius muscle development",
        image: "",
        videoLink: "",
      },
      {
        id: 11,
        name: "Behind the Neck Press",
        category: "Shoulders",
        difficulty: "Advanced",
        sets: 3,
        reps: "8-10",
        restTime: "60s",
        musclesTargeted: ["Rear Delts", "Side Delts"],
        equipment: ["Barbell"],
        instructions: [
          "Sit or stand with barbell behind neck",
          "Grip bar wider than shoulder-width",
          "Press bar overhead until arms extended",
          "Lower with control to starting position",
        ],
        benefits: "Advanced shoulder development exercise",
        image: "",
        videoLink: "",
      },
      {
        id: 12,
        name: "Landmine Press",
        category: "Shoulders",
        difficulty: "Intermediate",
        sets: 3,
        reps: "10-12 each side",
        restTime: "60s",
        musclesTargeted: ["Front Delts", "Upper Chest"],
        equipment: ["Barbell", "Landmine"],
        instructions: [
          "Position barbell in landmine attachment",
          "Stand facing barbell and grip end",
          "Press barbell upward and forward",
          "Lower with control to starting position",
        ],
        benefits: "Shoulder-friendly pressing variation",
        image: "",
        videoLink: "",
      },
      {
        id: 13,
        name: "Plate Raises",
        category: "Shoulders",
        difficulty: "Beginner",
        sets: 3,
        reps: "15-20",
        restTime: "45s",
        musclesTargeted: ["Front Delts", "Core"],
        equipment: ["Weight Plate"],
        instructions: [
          "Stand holding weight plate with both hands",
          "Raise plate forward to shoulder height",
          "Keep arms straight throughout movement",
          "Lower with control to starting position",
        ],
        benefits: "Targets front delts with unique grip",
        image: "",
        videoLink: "",
      },
      {
        id: 14,
        name: "Machine Shoulder Press",
        category: "Shoulders",
        difficulty: "Beginner",
        sets: 3,
        reps: "10-12",
        restTime: "60s",
        musclesTargeted: ["All Deltoid Heads"],
        equipment: ["Shoulder Press Machine"],
        instructions: [
          "Sit in machine with back against pad",
          "Grip handles at shoulder level",
          "Press handles overhead until arms extended",
          "Lower with control to starting position",
        ],
        benefits: "Stable shoulder pressing movement",
        image: "",
        videoLink: "",
      },
      {
        id: 15,
        name: "Kettlebell Press",
        category: "Shoulders",
        difficulty: "Intermediate",
        sets: 3,
        reps: "8-12 each side",
        restTime: "60s",
        musclesTargeted: ["Shoulders", "Core Stability"],
        equipment: ["Kettlebell"],
        instructions: [
          "Clean kettlebell to shoulder position",
          "Press kettlebell overhead with palm facing forward",
          "Keep core tight throughout movement",
          "Lower with control to starting position",
        ],
        benefits: "Builds shoulder stability and strength",
        image: "",
        videoLink: "",
      },
    ],

    Arms: [
      {
        id: 1,
        name: "Bicep Curls",
        category: "Arms",
        difficulty: "Beginner",
        sets: 3,
        reps: "12-15",
        restTime: "45s",
        musclesTargeted: ["Biceps"],
        equipment: ["Dumbbells"],
        instructions: [
          "Stand holding dumbbells at sides with palms forward",
          "Curl one arm up towards shoulder",
          "Squeeze bicep at top of movement",
          "Lower with control and alternate arms",
        ],
        benefits: "Builds bicep size and strength",
        image: "https://i.postimg.cc/bY0GQVnn/download_(12).jpg",
        videoLink: "https://i.postimg.cc/441dK7CZ/download_(12).gif",
      },
      {
        id: 2,
        name: "Tricep Pushdowns",
        category: "Arms",
        difficulty: "Beginner",
        sets: 3,
        reps: "12-15",
        restTime: "45s",
        musclesTargeted: ["Triceps"],
        equipment: ["Cable Machine"],
        instructions: [
          "Stand facing cable machine with rope attachment",
          "Grip rope with palms facing each other",
          "Push rope down until arms are fully extended",
          "Return with control to starting position",
        ],
        benefits: "Isolates and develops triceps",
        image: "",
        videoLink: "",
      },
      {
        id: 3,
        name: "Hammer Curls",
        category: "Arms",
        difficulty: "Beginner",
        sets: 3,
        reps: "12-15",
        restTime: "45s",
        musclesTargeted: ["Brachialis", "Forearms"],
        equipment: ["Dumbbells"],
        instructions: [
          "Stand holding dumbbells with palms facing each other",
          "Curl both arms up simultaneously",
          "Keep palms facing each other throughout movement",
          "Lower with control to starting position",
        ],
        benefits: "Builds arm thickness and forearm strength",
        image: "",
        videoLink: "",
      },
      {
        id: 4,
        name: "Skull Crushers",
        category: "Arms",
        difficulty: "Intermediate",
        sets: 3,
        reps: "10-12",
        restTime: "45s",
        musclesTargeted: ["Triceps"],
        equipment: ["EZ Bar", "Bench"],
        instructions: [
          "Lie on bench holding EZ bar above chest",
          "Lower bar towards forehead by bending elbows",
          "Keep upper arms stationary",
          "Extend arms back to starting position",
        ],
        benefits: "Targets long head of triceps for arm size",
        image: "",
        videoLink: "",
      },
      {
        id: 5,
        name: "Preacher Curls",
        category: "Arms",
        difficulty: "Intermediate",
        sets: 3,
        reps: "10-12",
        restTime: "45s",
        musclesTargeted: ["Biceps"],
        equipment: ["Preacher Bench", "Dumbbells"],
        instructions: [
          "Sit at preacher bench with arms resting on pad",
          "Curl dumbbell up towards shoulders",
          "Squeeze bicep at top of movement",
          "Lower with control to starting position",
        ],
        benefits: "Isolates biceps and prevents cheating",
        image: "",
        videoLink: "",
      },
      {
        id: 6,
        name: "Close Grip Bench Press",
        category: "Arms",
        difficulty: "Intermediate",
        sets: 3,
        reps: "8-12",
        restTime: "60s",
        musclesTargeted: ["Triceps", "Chest"],
        equipment: ["Barbell", "Bench"],
        instructions: [
          "Lie on bench with hands close together",
          "Lower bar to lower chest",
          "Press up while keeping elbows close to body",
          "Focus on triceps engagement",
        ],
        benefits: "Compound movement for triceps development",
        image: "",
        videoLink: "",
      },
      {
        id: 7,
        name: "Concentration Curls",
        category: "Arms",
        difficulty: "Beginner",
        sets: 3,
        reps: "12-15 each arm",
        restTime: "45s",
        musclesTargeted: ["Biceps Peak"],
        equipment: ["Dumbbells"],
        instructions: [
          "Sit on bench with legs apart",
          "Rest elbow on inner thigh",
          "Curl dumbbell up towards shoulder",
          "Squeeze bicep at top position",
        ],
        benefits: "Isolates biceps for peak development",
        image: "",
        videoLink: "",
      },
      {
        id: 8,
        name: "Overhead Tricep Extensions",
        category: "Arms",
        difficulty: "Intermediate",
        sets: 3,
        reps: "10-12",
        restTime: "45s",
        musclesTargeted: ["Triceps Long Head"],
        equipment: ["Dumbbell", "Cable"],
        instructions: [
          "Stand or sit holding dumbbell overhead",
          "Lower dumbbell behind head by bending elbows",
          "Keep upper arms close to head",
          "Extend arms back to starting position",
        ],
        benefits: "Targets long head of triceps",
        image: "",
        videoLink: "",
      },
      {
        id: 9,
        name: "Barbell Curls",
        category: "Arms",
        difficulty: "Beginner",
        sets: 3,
        reps: "10-12",
        restTime: "45s",
        musclesTargeted: ["Biceps", "Forearms"],
        equipment: ["Barbell"],
        instructions: [
          "Stand holding barbell with underhand grip",
          "Curl barbell up towards shoulders",
          "Keep elbows close to body",
          "Lower with control to starting position",
        ],
        benefits: "Builds overall bicep mass",
        image: "",
        videoLink: "",
      },
      {
        id: 10,
        name: "Dips",
        category: "Arms",
        difficulty: "Intermediate",
        sets: 3,
        reps: "8-12",
        restTime: "60s",
        musclesTargeted: ["Triceps", "Chest"],
        equipment: ["Parallel Bars"],
        instructions: [
          "Grip parallel bars and lift yourself up",
          "Keep body upright to emphasize triceps",
          "Lower until elbows at 90 degrees",
          "Push back up to starting position",
        ],
        benefits: "Bodyweight triceps builder",
        image: "",
        videoLink: "",
      },
      {
        id: 11,
        name: "Incline Dumbbell Curls",
        category: "Arms",
        difficulty: "Intermediate",
        sets: 3,
        reps: "10-12",
        restTime: "45s",
        musclesTargeted: ["Biceps", "Brachialis"],
        equipment: ["Dumbbells", "Incline Bench"],
        instructions: [
          "Sit on incline bench with arms hanging",
          "Curl dumbbells up towards shoulders",
          "Keep palms facing forward",
          "Lower with control to starting position",
        ],
        benefits: "Stretches biceps for greater range of motion",
        image: "",
        videoLink: "",
      },
      {
        id: 12,
        name: "Cable Curls",
        category: "Arms",
        difficulty: "Beginner",
        sets: 3,
        reps: "12-15",
        restTime: "45s",
        musclesTargeted: ["Biceps"],
        equipment: ["Cable Machine"],
        instructions: [
          "Stand facing cable machine with bar attachment",
          "Grip bar with underhand grip",
          "Curl bar towards shoulders",
          "Lower with control to starting position",
        ],
        benefits: "Constant tension on biceps",
        image: "",
        videoLink: "",
      },
      {
        id: 13,
        name: "Reverse Curls",
        category: "Arms",
        difficulty: "Intermediate",
        sets: 3,
        reps: "12-15",
        restTime: "45s",
        musclesTargeted: ["Forearms", "Brachioradialis"],
        equipment: ["Barbell"],
        instructions: [
          "Stand holding barbell with overhand grip",
          "Curl barbell up towards shoulders",
          "Keep elbows close to body",
          "Lower with control to starting position",
        ],
        benefits: "Builds forearm and brachioradialis strength",
        image: "",
        videoLink: "",
      },
      {
        id: 14,
        name: "Tricep Kickbacks",
        category: "Arms",
        difficulty: "Beginner",
        sets: 3,
        reps: "12-15 each arm",
        restTime: "45s",
        musclesTargeted: ["Triceps"],
        equipment: ["Dumbbells"],
        instructions: [
          "Bend at hips with back straight",
          "Hold dumbbell with elbow bent at 90 degrees",
          "Extend arm back until straight",
          "Return with control to starting position",
        ],
        benefits: "Isolates triceps with controlled movement",
        image: "",
        videoLink: "",
      },
      {
        id: 15,
        name: "Zottman Curls",
        category: "Arms",
        difficulty: "Intermediate",
        sets: 3,
        reps: "10-12",
        restTime: "45s",
        musclesTargeted: ["Biceps", "Forearms"],
        equipment: ["Dumbbells"],
        instructions: [
          "Stand holding dumbbells with palms forward",
          "Curl dumbbells up towards shoulders",
          "At top, rotate palms to face downward",
          "Lower dumbbells with reverse grip",
        ],
        benefits: "Targets both biceps and forearms",
        image: "",
        videoLink: "",
      },
    ],

    Legs: [
      {
        id: 1,
        name: "Squats",
        category: "Legs",
        difficulty: "Intermediate",
        sets: 4,
        reps: "8-12",
        restTime: "60-90s",
        musclesTargeted: ["Quads", "Glutes", "Hamstrings"],
        equipment: ["Barbell"],
        instructions: [
          "Stand with barbell across upper back",
          "Keep chest up and back straight",
          "Lower until thighs are parallel to floor",
          "Drive through heels to return to standing",
        ],
        benefits: "King of leg exercises, builds overall leg strength",
        image: "",
        videoLink: "",
      },
      {
        id: 2,
        name: "Leg Press",
        category: "Legs",
        difficulty: "Beginner",
        sets: 4,
        reps: "10-15",
        restTime: "60s",
        musclesTargeted: ["Quads", "Glutes"],
        equipment: ["Leg Press Machine"],
        instructions: [
          "Sit in leg press machine with feet shoulder-width",
          "Lower weight until knees are at 90 degrees",
          "Press platform away until legs are extended",
          "Don't lock knees at top",
        ],
        benefits: "Builds quad strength with less spinal loading",
        image: "",
        videoLink: "",
      },
      {
        id: 3,
        name: "Lunges",
        category: "Legs",
        difficulty: "Beginner",
        sets: 3,
        reps: "10-12 each leg",
        restTime: "45s",
        musclesTargeted: ["Quads", "Glutes", "Hamstrings"],
        equipment: ["Bodyweight", "Dumbbells (optional)"],
        instructions: [
          "Stand with feet together",
          "Step forward with one leg and lower hips",
          "Keep front knee behind toes",
          "Push back to starting position",
        ],
        benefits: "Develops leg strength and balance",
        image: "",
        videoLink: "",
      },
      {
        id: 4,
        name: "Romanian Deadlifts",
        category: "Legs",
        difficulty: "Intermediate",
        sets: 3,
        reps: "10-12",
        restTime: "60s",
        musclesTargeted: ["Hamstrings", "Glutes"],
        equipment: ["Barbell"],
        instructions: [
          "Stand holding barbell with overhand grip",
          "Keep legs slightly bent and back straight",
          "Hinge at hips, lowering barbell down legs",
          "Return to standing by squeezing glutes",
        ],
        benefits: "Excellent for hamstring and glute development",
        image: "",
        videoLink: "",
      },
      {
        id: 5,
        name: "Calf Raises",
        category: "Legs",
        difficulty: "Beginner",
        sets: 4,
        reps: "15-20",
        restTime: "30s",
        musclesTargeted: ["Calves"],
        equipment: ["Calf Raise Machine"],
        instructions: [
          "Stand on calf raise machine with shoulders under pads",
          "Lower heels as far as possible",
          "Raise onto toes as high as possible",
          "Squeeze calves at top of movement",
        ],
        benefits: "Builds calf size and definition",
        image: "",
        videoLink: "",
      },
      {
        id: 6,
        name: "Leg Extensions",
        category: "Legs",
        difficulty: "Beginner",
        sets: 3,
        reps: "12-15",
        restTime: "45s",
        musclesTargeted: ["Quads"],
        equipment: ["Leg Extension Machine"],
        instructions: [
          "Sit in machine with shins against pads",
          "Extend legs until they are straight",
          "Squeeze quads at top position",
          "Lower with control to starting position",
        ],
        benefits: "Isolates quadriceps muscles",
        image: "",
        videoLink: "",
      },
      {
        id: 7,
        name: "Hamstring Curls",
        category: "Legs",
        difficulty: "Beginner",
        sets: 3,
        reps: "12-15",
        restTime: "45s",
        musclesTargeted: ["Hamstrings"],
        equipment: ["Leg Curl Machine"],
        instructions: [
          "Lie face down on machine with ankles under pads",
          "Curl legs up towards glutes",
          "Squeeze hamstrings at top position",
          "Lower with control to starting position",
        ],
        benefits: "Isolates hamstring development",
        image: "",
        videoLink: "",
      },
      {
        id: 8,
        name: "Bulgarian Split Squats",
        category: "Legs",
        difficulty: "Intermediate",
        sets: 3,
        reps: "10-12 each leg",
        restTime: "60s",
        musclesTargeted: ["Quads", "Glutes"],
        equipment: ["Bench", "Dumbbells"],
        instructions: [
          "Stand facing away from bench",
          "Place one foot on bench behind you",
          "Lower until front thigh is parallel to floor",
          "Push back up to starting position",
        ],
        benefits: "Unilateral leg strength development",
        image: "",
        videoLink: "",
      },
      {
        id: 9,
        name: "Hack Squats",
        category: "Legs",
        difficulty: "Intermediate",
        sets: 3,
        reps: "8-12",
        restTime: "60s",
        musclesTargeted: ["Quads", "Glutes"],
        equipment: ["Hack Squat Machine"],
        instructions: [
          "Position yourself in hack squat machine",
          "Place shoulders under pads and back against support",
          "Lower until knees at 90 degrees",
          "Push back to starting position",
        ],
        benefits: "Quad-focused squat variation",
        image: "",
        videoLink: "",
      },
      {
        id: 10,
        name: "Step-Ups",
        category: "Legs",
        difficulty: "Beginner",
        sets: 3,
        reps: "10-12 each leg",
        restTime: "45s",
        musclesTargeted: ["Quads", "Glutes"],
        equipment: ["Bench", "Dumbbells"],
        instructions: [
          "Stand facing bench or platform",
          "Step up with one leg onto bench",
          "Bring other leg up to stand on bench",
          "Step back down and alternate legs",
        ],
        benefits: "Functional leg strength development",
        image: "",
        videoLink: "",
      },
      {
        id: 11,
        name: "Good Mornings",
        category: "Legs",
        difficulty: "Intermediate",
        sets: 3,
        reps: "10-12",
        restTime: "60s",
        musclesTargeted: ["Hamstrings", "Glutes", "Lower Back"],
        equipment: ["Barbell"],
        instructions: [
          "Stand with barbell across upper back",
          "Keep legs slightly bent",
          "Hinge at hips until torso parallel to floor",
          "Return to standing by squeezing glutes",
        ],
        benefits: "Hamstring and posterior chain developer",
        image: "",
        videoLink: "",
      },
      {
        id: 12,
        name: "Pistol Squats",
        category: "Legs",
        difficulty: "Advanced",
        sets: 3,
        reps: "5-8 each leg",
        restTime: "60s",
        musclesTargeted: ["Quads", "Glutes", "Core"],
        equipment: ["Bodyweight"],
        instructions: [
          "Stand on one leg with other leg extended",
          "Lower into squat on single leg",
          "Keep chest up and balance",
          "Push back up to starting position",
        ],
        benefits: "Advanced unilateral leg strength",
        image: "",
        videoLink: "",
      },
      {
        id: 13,
        name: "Box Jumps",
        category: "Legs",
        difficulty: "Intermediate",
        sets: 4,
        reps: "8-10",
        restTime: "60s",
        musclesTargeted: ["Quads", "Glutes", "Calves"],
        equipment: ["Plyo Box"],
        instructions: [
          "Stand facing box with feet shoulder-width",
          "Swing arms and jump onto box",
          "Land softly with knees slightly bent",
          "Step back down and repeat",
        ],
        benefits: "Develops explosive power in legs",
        image: "",
        videoLink: "",
      },
      {
        id: 14,
        name: "Sumo Squats",
        category: "Legs",
        difficulty: "Beginner",
        sets: 3,
        reps: "12-15",
        restTime: "45s",
        musclesTargeted: ["Inner Thighs", "Glutes", "Quads"],
        equipment: ["Barbell", "Dumbbell"],
        instructions: [
          "Stand with feet wider than shoulder-width",
          "Hold weight with both hands",
          "Lower into squat keeping chest up",
          "Push back to starting position",
        ],
        benefits: "Targets inner thighs and glutes",
        image: "",
        videoLink: "",
      },
      {
        id: 15,
        name: "Walking Lunges",
        category: "Legs",
        difficulty: "Intermediate",
        sets: 3,
        reps: "10-12 steps each leg",
        restTime: "60s",
        musclesTargeted: ["Quads", "Glutes", "Hamstrings"],
        equipment: ["Dumbbells"],
        instructions: [
          "Stand holding dumbbells at sides",
          "Step forward into lunge position",
          "Push off back foot to bring it forward",
          "Continue alternating legs while moving forward",
        ],
        benefits: "Dynamic leg strength and coordination",
        image: "",
        videoLink: "",
      },
    ],

    WeightLoss: [
      {
        id: 1,
        name: "Burpees",
        category: "WeightLoss",
        difficulty: "Intermediate",
        sets: 4,
        reps: "10-15",
        restTime: "30s",
        caloriesBurned: "10-15 per rep",
        equipment: ["Bodyweight"],
        instructions: [
          "Start in standing position",
          "Drop into squat position with hands on floor",
          "Kick feet back into plank position",
          "Do a push-up, then return to squat and jump up",
        ],
        benefits: "Full body exercise that maximizes calorie burn",
        image: "",
        videoLink: "",
      },
      {
        id: 2,
        name: "Kettlebell Swings",
        category: "WeightLoss",
        difficulty: "Intermediate",
        sets: 4,
        reps: "15-20",
        restTime: "45s",
        caloriesBurned: "200-300 per session",
        equipment: ["Kettlebell"],
        instructions: [
          "Stand with feet wider than shoulders",
          "Hold kettlebell with both hands",
          "Hinge at hips and swing kettlebell between legs",
          "Thrust hips forward to swing kettlebell to chest height",
        ],
        benefits: "Builds explosive power and burns fat efficiently",
        image: "",
        videoLink: "",
      },
      {
        id: 3,
        name: "Box Jumps",
        category: "WeightLoss",
        difficulty: "Intermediate",
        sets: 4,
        reps: "10-12",
        restTime: "45s",
        caloriesBurned: "150-250 per session",
        equipment: ["Plyo Box"],
        instructions: [
          "Stand facing box with feet shoulder-width",
          "Swing arms and jump onto box",
          "Land softly with knees slightly bent",
          "Step back down and repeat",
        ],
        benefits: "Plyometric exercise that boosts metabolism",
        image: "",
        videoLink: "",
      },
      {
        id: 4,
        name: "Battle Ropes",
        category: "WeightLoss",
        difficulty: "Beginner",
        sets: 4,
        duration: "30-45 seconds",
        restTime: "30s",
        caloriesBurned: "300-400 per session",
        equipment: ["Battle Ropes"],
        instructions: [
          "Stand with feet shoulder-width apart",
          "Hold one rope in each hand",
          "Alternate arms in wave motion",
          "Maintain fast pace for duration",
        ],
        benefits: "High-intensity cardio that builds upper body endurance",
        image: "",
        videoLink: "",
      },
      {
        id: 5,
        name: "Rowing Machine",
        category: "WeightLoss",
        difficulty: "Beginner",
        duration: "20-30 minutes",
        intensity: "Moderate-High",
        caloriesBurned: "400-600",
        equipment: ["Rowing Machine"],
        instructions: [
          "Start with legs extended, leaning slightly back",
          "Pull handle to chest while leaning back",
          "Extend arms forward, then bend knees to return",
          "Maintain smooth, continuous motion",
        ],
        benefits: "Full body cardio that builds endurance",
        image: "",
        videoLink: "",
      },
      {
        id: 6,
        name: "Jump Squats",
        category: "WeightLoss",
        difficulty: "Intermediate",
        sets: 4,
        reps: "15-20",
        restTime: "45s",
        caloriesBurned: "200-300 per session",
        equipment: ["Bodyweight"],
        instructions: [
          "Start in squat position",
          "Explosively jump as high as possible",
          "Land softly and immediately go into next squat",
          "Maintain continuous rhythm",
        ],
        benefits: "Plyometric leg exercise for fat burning",
        image: "",
        videoLink: "",
      },
      {
        id: 7,
        name: "Mountain Climbers",
        category: "WeightLoss",
        difficulty: "Beginner",
        sets: 4,
        reps: "30-45 seconds",
        restTime: "30s",
        caloriesBurned: "150-250 per session",
        equipment: ["Mat"],
        instructions: [
          "Start in plank position",
          "Bring one knee towards chest",
          "Quickly switch legs in running motion",
          "Maintain fast pace and tight core",
        ],
        benefits: "Core and cardio combination exercise",
        image: "",
        videoLink: "",
      },
      {
        id: 8,
        name: "High Knees",
        category: "WeightLoss",
        difficulty: "Beginner",
        sets: 4,
        reps: "30-45 seconds",
        restTime: "30s",
        caloriesBurned: "100-200 per session",
        equipment: ["Bodyweight"],
        instructions: [
          "Stand with feet hip-width apart",
          "Run in place bringing knees to chest height",
          "Pump arms vigorously",
          "Maintain fast, controlled pace",
        ],
        benefits: "Cardio exercise that improves coordination",
        image: "",
        videoLink: "",
      },
      {
        id: 9,
        name: "Jumping Jacks",
        category: "WeightLoss",
        difficulty: "Beginner",
        sets: 4,
        reps: "30-45 seconds",
        restTime: "30s",
        caloriesBurned: "100-150 per session",
        equipment: ["Bodyweight"],
        instructions: [
          "Stand with feet together and arms at sides",
          "Jump while spreading legs and raising arms overhead",
          "Return to starting position",
          "Maintain steady rhythm",
        ],
        benefits: "Full body cardio warm-up exercise",
        image: "",
        videoLink: "",
      },
      {
        id: 10,
        name: "Sprint Intervals",
        category: "WeightLoss",
        difficulty: "Advanced",
        sets: 8,
        duration: "30 seconds sprint, 60 seconds walk",
        restTime: "60s",
        caloriesBurned: "400-600 per session",
        equipment: ["Running Shoes"],
        instructions: [
          "Warm up with 5 minutes light jogging",
          "Sprint all-out for 30 seconds",
          "Walk or jog for 60 seconds recovery",
          "Repeat for 8-10 cycles",
        ],
        benefits: "Maximum calorie burn through HIIT",
        image: "",
        videoLink: "",
      },
      {
        id: 11,
        name: "Medicine Ball Slams",
        category: "WeightLoss",
        difficulty: "Intermediate",
        sets: 4,
        reps: "15-20",
        restTime: "45s",
        caloriesBurned: "200-300 per session",
        equipment: ["Medicine Ball"],
        instructions: [
          "Stand holding medicine ball overhead",
          "Slam ball down to ground with force",
          "Squat to pick up ball",
          "Return to standing and repeat",
        ],
        benefits: "Full body explosive movement for fat loss",
        image: "",
        videoLink: "",
      },
      {
        id: 12,
        name: "Skater Jumps",
        category: "WeightLoss",
        difficulty: "Intermediate",
        sets: 4,
        reps: "20-30 total",
        restTime: "45s",
        caloriesBurned: "150-250 per session",
        equipment: ["Bodyweight"],
        instructions: [
          "Start standing with feet together",
          "Jump sideways to right, landing on right foot",
          "Immediately jump sideways to left",
          "Continue alternating sides",
        ],
        benefits: "Lateral movement cardio exercise",
        image: "",
        videoLink: "",
      },
      {
        id: 13,
        name: "Bicycle Crunches",
        category: "WeightLoss",
        difficulty: "Beginner",
        sets: 4,
        reps: "20-30 each side",
        restTime: "30s",
        caloriesBurned: "100-200 per session",
        equipment: ["Mat"],
        instructions: [
          "Lie on back with hands behind head",
          "Bring right elbow to left knee while extending right leg",
          "Alternate sides in pedaling motion",
          "Maintain continuous movement",
        ],
        benefits: "Core exercise with cardio benefits",
        image: "",
        videoLink: "",
      },
      {
        id: 14,
        name: "Plank Jacks",
        category: "WeightLoss",
        difficulty: "Intermediate",
        sets: 4,
        reps: "20-30",
        restTime: "30s",
        caloriesBurned: "150-250 per session",
        equipment: ["Mat"],
        instructions: [
          "Start in plank position",
          "Jump feet out wide like jumping jack",
          "Jump feet back together",
          "Maintain tight core throughout",
        ],
        benefits: "Core stability with cardio element",
        image: "",
        videoLink: "",
      },
      {
        id: 15,
        name: "TRX Suspension Trainer Exercises",
        category: "WeightLoss",
        difficulty: "Intermediate",
        sets: 4,
        reps: "30-45 seconds each exercise",
        restTime: "30s",
        caloriesBurned: "300-500 per session",
        equipment: ["TRX Suspension Trainer"],
        instructions: [
          "Perform TRX mountain climbers",
          "TRX jump squats",
          "TRX pikes",
          "TRX atomic push-ups in circuit",
        ],
        benefits: "Full body suspension training for fat loss",
        image: "",
        videoLink: "",
      },
    ],
  },
};

const UploadExercises = () => {
  const uploadData = async () => {
    try {
      const batch = writeBatch(db);

      Object.keys(exercisesData.Exercises).forEach((muscleGroup) => {
        exercisesData.Exercises[muscleGroup].forEach((exercise) => {
          const docRef = doc(collection(db, "Exercises"));
          batch.set(docRef, {
            ...exercise,
            muscleGroup, // اسم الجزء (chest, back...)
            createdAt: serverTimestamp(),
          });
        });
      });

      await batch.commit();
      alert("✅ تم رفع جميع التمارين بنجاح!");
    } catch (error) {
      console.error("❌ خطأ أثناء رفع التمارين:", error);
      alert("حدث خطأ أثناء الرفع");
    }
  };

  return (
    <div style={{ padding: "20px", background: "#111", color: "#fff" }}>
      <h2>🏋️‍♂️ رفع بيانات التمارين إلى Firebase</h2>
      <button
        onClick={uploadData}
        style={{
          marginTop: "20px",
          padding: "10px 20px",
          background: "#4cc9f0",
          border: "none",
          borderRadius: "8px",
          cursor: "pointer",
        }}
      >
        رفع التمارين الآن 🚀
      </button>
    </div>
  );
};

export default UploadExercises;
